### PR TITLE
Lectures 17/18 (remote computing)

### PR DESCRIPTION
**Pull request by k8hertweck**
We have two lectures for remote computing.

@matsen has already listed the following as options for the first day:

* the structure of the cluster: servers vs cluster nodes
* processes: foreground, background, killing, `top`
* passwordless login with ssh keys
* tmux (!!)
* grabnode and cluster job submission
* environment variables; PATH
* command line git

Other options, perhaps for the second day:
* slurm (job submission)
* containers
* Nextflow

### CODE REVIEW

**Comment by matsen** [comment]
I also noticed that we haven't talked at all about wildcards or regexes. 
We need to do something about scp. Perhaps rsync?

Perhaps https://osca.bioconductor.org/overview.html#data-processing-and-downstream-analysis as a motivating example?

**Comment by k8hertweck** [comment]
Jesse is covering regex (briefly) with Python: https://github.com/fredhutchio/tfcb_2019/blob/master/lectures/lecture13/lecture13.ipynb

**Comment by matsen** [comment]
From the feedback:

* For next time, I should have more checks about "are you in the right directory"

Things to do for the next course:
* I didn't cover `cp`, but this will go nicely with `scp` for this lecture
* describe why vim
* if we submit to the cluster we will see automatically why shell scripts are key
* people would like a cheat sheet
* address these questions in the beginning of the next class
* cover calling an external command in python
* cover uncompressing things from the shell
* wildcards! describe them.

**Comment by matsen** [comment]
OK, @k8hertweck ! I've pushed my course material for Thursday, and rebased off of master.

My plan is to spend a bunch of the time talking and giving demos (topics in the md file in the `slides` dir), but I added some interactive exercises in the README as well. I imagine that you'll want to add some reminders etc before merging.

I pushed everything else to lecture 18, and updated that README. You'll have some flexibility about how you want to run things there, and let me know how I can help.

**Pull request merged**
