### PR TITLE
Include lecture 3 as Markdown document

### PR DESCRIPTION
**Pull request by trvrb**
@k8hertweck: Here is lecture 3. It should be ready for review. Thank you!

### CODE REVIEW

**Review by k8hertweck — APPROVED** [review]
Happy with this as well. Same note about project organization. There are some pieces I think are especially important for the data management section: we can't highlight READMEs too much, especially in the context of documenting metadata (and I don't think we'll really talk much about metadata in other places?). I'd be happy to add some links about this since I'm developing content for fredhutch.io courses related to the topic.

**Comment by trvrb** [comment]
Thanks Kate! Any suggestions that you have on documenting metadata would be great. Feel free to add content / examples.

**Comment by k8hertweck** [comment]
@trvrb I've added a quick list of metadata-related guidelines, and clarified a few other points as well. Give me the thumbs up and I'll go ahead and merge.

**Comment by trvrb** [comment]
Thanks for the additions Kate! Very helpful.

**Pull request merged**
