### PR TITLE
lecture 14 and homework 6

### PR DESCRIPTION
**Pull request by jbloom**
@k8hertweck: This pull request adds lecture 14 and homework 7.

The lecture 14 material is just contained in a merged Jupyter notebook for lectures 13 and 14.

The homework extends the in-class analysis, and is provided at the bottom of the Jupyter notebook.

Can you let me know if this appears OK, and if so merge pull request?

### CODE REVIEW

**Comment by k8hertweck** [comment]
This looks great, thanks!

I'm going to split the homework into a separate file and add to `homeworks/homework06` so I can administer through GitHub Classroom. 

Since students probably added content to their notebook in the last class, adding this to the previous notebook can create merge conflicts (I tried this on my own, and a even the version of Python reported in the notebook can cause pulling to fail). Is it ok if I split that into a separate notebook as well? I wish jupyter notebooks played better with github!

**Comment by jbloom** [comment]
@k8hertweck: I'd like to keep a merged notebook as some of the stuff for the current lecture will utilize code written for lecture 13.

So instead can you just make the new `lecture13and14.ipynb` the notebook for lecture 14, and I guess some material will be duplicated relative to the prior notebook. 

It's fine to move a version of the homework to a new location, but can you also keep it at the end of the lecture so I can just go through it from the notebook in class?

**Comment by jbloom** [comment]
Let me know if you are able to make these changes; otherwise I can do so.

**Comment by jbloom** [comment]
@k8hertweck: thanks for changes. Are you still updating, our should I finalize re-organization and merge to have ready for lecture?

**Comment by k8hertweck** [comment]
I'm so sorry I missed your note above about leaving the homework in the original notebook! 

I'm writing the README for lecture 14 with the usual reminders; please make whatever changes you'd like and I'll adjust my links as necessary.

**Comment by jbloom** [comment]
@k8hertweck: OK, all aforementioned changes are made. Can you merge this version now?

**Pull request merged**
