### PR TITLE
Lecture06 first draft

### PR DESCRIPTION
**Pull request by rasi**
@k8hertweck I have skipped lecture05 for now. I plan to cover topics from the book https://serialmentor.com/dataviz/ for this lecture. I am still thinking about which topics from this book will be most useful. If you have thoughts, it will be great to discuss them sometime this week.

### CODE REVIEW

**Comment by k8hertweck** [comment]
Happy to talk about this!

**Comment by rasi** [comment]
Thanks, @k8hertweck. Are you available on Wed,Thurs, Fri this week at 3p?

**Comment by k8hertweck** [comment]
Yes, I can do any of those. Wednesday?

**Comment by rasi** [comment]
> Yes, I can do any of those. Wednesday?

Great I can come to your office on Wed at 3p.

**Pull request merged**
