### PR TITLE
lecture08, genomic data in R

### PR DESCRIPTION
**Pull request by k8hertweck**

### CODE REVIEW

**Comment by k8hertweck** [comment]
I'll add a few notes here as I work through the analysis.

First, it may be useful to explicitly say that all downloaded data files should be placed in a directory with the scripts (I'll include this in the README, and you will probably also need to say this as you work through materials in class)

**Comment by gavinha** [comment]
Hi @k8hertweck 

If you have no concerns about the lecture materials, you can merge this PR.

Thanks,
Gavin

**Comment by k8hertweck** [comment]
This is awesome! The code runs very well as long as files are in the correct place (and named correctly). I'm concerned some students will have .gz files that are auto-expanded after download, which results in the R session aborting when running the chunk requiring the gzipped file. I'll add some notes to the readme, and double check with everyone at the start of class.

I really like how the slides include the files necessary for each tutorial. It looks like some of the file names are duplicated, though?

**Comment by k8hertweck** [comment]
I changed the output format from knitting to html, since PDF requires LaTeX and it's easier to not include an additional install. Happy to change back if necessary. I'm going ahead and merging to check links and whatnot but feel free to make additional changes before class.

**Pull request merged**
