### PR TITLE
Add initial draft of lecture 10 lecture as ipython notebook

### PR DESCRIPTION
**Pull request by phbradley**

### CODE REVIEW

**Comment by phbradley** [comment]
Not necessarily ready for prime-time, just trying to get things into place...

**Comment by phbradley** [comment]
@jbloom @k8hertweck I checked in a draft of lecture 10 which is going to be the "content" lecture for the two intro to python lectures. The schedule got slightly mixed up since Erick and I had to switch a date. So I'm doing python intro in lectures 10 (content) and 11 (work in class). This is mostly borrowed from last year right now, so I will probably be updating things

**Comment by k8hertweck** [comment]
@phbradley I'll be adding a README to this branch that includes the standard stuff for each lecture: learning objectives, description of files in the course materials, and reminders (mostly about homework due dates and whatnot). 

This notebook looks great; is the material for both lecture 10 and 11? 

It may help to know that students really appreciate having a bit of time to practice coding activities in class, which prepares them for homework. A few challenge exercises for in-class practice would make this the right amount of material for both lectures. 

I try to merge the PR for a lecture about noon on the day of class. The homework for this section (homework 5, intro to python, lectures 10 and 11) is set to be assigned on Tuesday, but is not due until Nov 7, so we could delay releasing it until Thursday if that would work better (and students are struggling with the current homework assignment due tomorrow, and would probably appreciate a break).

**Comment by phbradley** [comment]
@k8hertweck Thanks so much! Yes, my thought was that this was probably about right for both days assuming a fair amount of in-class practice time. Delaying the HW until Thursday also seems like a good idea. I will work on the notebook a bit more today, and then ping you when I'm happy with it. Does that sound OK? Any sense of whether it would be better to front load the material and leave most of Thursday for practice time, or balance practice more evenly between the two classes?

**Comment by k8hertweck** [comment]
Excellent, this plan sounds great and I'll update things accordingly. 

This class seems to overestimate their understanding of material, so it would be better to include challenges early so that they can identify things they don't understand.

**Comment by phbradley** [comment]
@k8hertweck Nitty gritty question here: in the jupyter notebook file the kernel seems to have a name, like "Python 3" or "py36" or whatever. Is there a standard kernel name that I should use, ie the one that will match whatever kernel the students have defined and are running? I don't think it's the end of the world if it doesn't -- they just will have to select the kernel from the list of installed ones on their system. But might be nice.

I'm looking at the end of the notebook file, e.g.:

 "metadata": {
  "kernelspec": {
   "display_name": "py36",
   "language": "python",
   "name": "py36"
  },

**Comment by k8hertweck** [comment]
I think the default for Anaconda (at least on Mac) is "Python 3", so I'd recommend that.

**Comment by phbradley** [comment]
@k8hertweck I added a few "practice" sessions interspersed early on, up to the point where I think we might reasonably get tomorrow.

I've still got all the material in even though the latter part will move to the next class. It's not optimal but I'd rather just play it by ear, then define the lecture11 notebook once Tuesday's class is over. If that sounds OK to you.

Again, the HW will be ready to be assigned on Thursday rather than tomorrow.

I also set the kernel name to "Python 3" So as far as I'm concerned it's good to go. If I get more time tomorrow morning I may add a few more practice sessions...

**Comment by k8hertweck** [comment]
I've added the README content that includes the homework dude dates (and I'll update the repo README as well). Happy to merge whenever you give the go-ahead (and I'll push the button by early afternoon regardless).

**Comment by phbradley** [comment]
Thanks @k8hertweck -- please do merge.

**Pull request merged**
