### PR TITLE
Lecture04 first draft

### PR DESCRIPTION
**Pull request by rasi**
I also reordered my lectures so that I am teaching data visualization using ggplot2 before data munging with dplyr

### CODE REVIEW

**Comment by rasi** [comment]
@k8hertweck Can you please update the lecture schedule in the README.md in this pull request so that the order of my lectures is correct? Thanks!

**Comment by k8hertweck** [comment]
I've updated README.md in master.

**Comment by k8hertweck** [comment]
Is it ok if I rename your `README.org` and `README.html` files to `lecture.org` and `lecture.html`, so I can include the standard info (learning objectives, class materials, and reminders) in `README.md` to match the other lessons?

**Comment by rasi** [comment]
Sure, that works.

**Comment by k8hertweck** [comment]
Let me know if this looks ok and I'lll merge. I'll go ahead and do this by noon the day of your lecture if I don't hear otherwise. Thanks @rasi !

**Comment by rasi** [comment]
@k8hertweck Your README.md looks great. I just added a small clarification. Edit as you wish and merge it with master.

**Pull request merged**
